#title in header
title: "Hi"

#main info
#owner
owner: ""
info: ""
#description
desc: "Romantic, Freely and Balanced."

#menu
menu:
  Movies: /movies
  Travel: /travel
  Album: /album
  # Music: /music
  # About: /about

#index/main page max show posts (in number)
max_post: 4

# Colors use hex color without #
# Theme color
tcolor: 0FA0CE

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/user.css

# social profile at the footer/bottom
footer: true
placename: Earth
placelink: https://en.wikipedia.org/wiki/Earth
github: https://github.com/yoyoiii
# linkedin: https://linkedin.com/in/adisaktijrs
# twitter: https://twitter.com/adisaktijrs
# instagram: https://instagram.com/adisaktijrs
# stackoverflow: https://stackoverflow.com/story/tobiasreithmeier
csdn: https://blog.csdn.net/sinat_35026778
email: "ueezhang@163.com"

# Misc
nanobar: /lib/nanobar.min.js
switch_light: ☀️
switch_dark: 🌑

# Picture enlargement
# picjs: /lib/pic.min.js

# favicon
favicon: /images/favicon.png
# thumbnail
thumbnail: /images/thumbnail.jpg

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: false
disqus_shortname: https-adisaktijrs-github-io

# Search
search: false

# Theme Color (use hex color without #)
theme_colors: [
  "A35C8F",
  "22A2C3",
  "E68C12",
  "A6D40D",
  "E6ADCF",
]


